### ISSUE TITLE
issue BTVN Buổi 1 

### ISSUE THREAD

**Issue by 0367592801** [anhchinh03102k/anhchinh03102k.github.io#1]
:v vẫn có issue buổi 1 nè, sorry vì check muộn cho e nhé. Ảnh đẹp đấy nhưng e nên để ảnh và câu thơ ở dưới vào 1 div vì 2 thẻ hr ở trên và dưới sẽ phân chia rõ ràng ranh giới 2 div rồi. Hơi sơ sài, thiếu sáng tạo. Nhìn chung thì hoàn thành bt! OK được! Tốt lắm e. 🤙  có mỗi a check bài cho nên đừng gọi chị nhá :V

**Comment by anhchinh03102k** [comment]
Vâng có gì sai anh cứ góp ý mạnh tay nhá
