### ISSUE TITLE
Issue BTVN Buổi 2 

### ISSUE THREAD

**Issue by 0367592801** [anhchinh03102k/anhchinh03102k.github.io#2]
Bài này tốt hơn nhiều bài trc này. Chia chuẩn đấy. Đẹp mắt, dễ nhìn, nchg là tốt lắm e. Cố gắng lên nhé, cứ thế phát huy. Lọt top  rồi đấy. Tuy còn nhiều bạn chưa nộp bài :v

**Comment by anhchinh03102k** [comment]
Em cảm ơn anh ạ.
